index:
  keywords:
    - python
    - django
    - bottle
    - pandas
    - ai
    - bot
    - bots
    - chatbot
    - chatbots
    - numpy
    - keras
    - sqlalchemy
    - blockchain
    - bitcoin
    - ether
    - pycon
    - ethereum
  phrases:
    - deep learning
    - import this
    - python software foundation

